name: workflow for the greeting action
on:
    push:
      branches: [dev]

jobs:
      greeting:
        runs-on: ubuntu-latest

        steps:
          - name: checkout repository
            uses: actions/checkout@v4

          - name: welcome message
            run: echo "hello world from the first repo"