name: Build and Test Pipeline

on:
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: building the application
        run: echo "building the application"

  test:
    runs-on: ubuntu-latest
    needs: build
      
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: testing the application
        run: echo "testing the application"
